# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Income = QtWidgets.QLineEdit(self.centralwidget)
        self.Income.setGeometry(QtCore.QRect(160, 50, 161, 31))
        self.Income.setText("")
        self.Income.setObjectName("Income")
        self.Lable_sum = QtWidgets.QLabel(self.centralwidget)
        self.Lable_sum.setGeometry(QtCore.QRect(30, 60, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lable_sum.setFont(font)
        self.Lable_sum.setObjectName("Lable_sum")
        self.Lable_3 = QtWidgets.QLabel(self.centralwidget)
        self.Lable_3.setGeometry(QtCore.QRect(30, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lable_3.setFont(font)
        self.Lable_3.setObjectName("Lable_3")
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setGeometry(QtCore.QRect(100, 130, 111, 31))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.Lable_1 = QtWidgets.QLabel(self.centralwidget)
        self.Lable_1.setGeometry(QtCore.QRect(30, 190, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lable_1.setFont(font)
        self.Lable_1.setObjectName("Lable_1")
        self.Lable_2 = QtWidgets.QLabel(self.centralwidget)
        self.Lable_2.setGeometry(QtCore.QRect(30, 230, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lable_2.setFont(font)
        self.Lable_2.setObjectName("Lable_2")
        self.label_Sum = QtWidgets.QLabel(self.centralwidget)
        self.label_Sum.setGeometry(QtCore.QRect(160, 190, 141, 21))
        self.label_Sum.setText("")
        self.label_Sum.setObjectName("label_Sum")
        self.label_SumTax = QtWidgets.QLabel(self.centralwidget)
        self.label_SumTax.setGeometry(QtCore.QRect(160, 230, 141, 21))
        self.label_SumTax.setText("")
        self.label_SumTax.setObjectName("label_SumTax")
        self.label_TaxProc = QtWidgets.QLabel(self.centralwidget)
        self.label_TaxProc.setGeometry(QtCore.QRect(100, 100, 141, 21))
        self.label_TaxProc.setText("")
        self.label_TaxProc.setObjectName("label_TaxProc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Lable_sum.setText(_translate("MainWindow", "Введите сумму:"))
        self.Lable_3.setText(_translate("MainWindow", "Налог:"))
        self.pushButton_Save.setText(_translate("MainWindow", "Сохранить"))
        self.Lable_1.setText(_translate("MainWindow", "Сумма дохода:"))
        self.Lable_2.setText(_translate("MainWindow", "Сумма налога:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
